booker.base-url=https://restful-booker.herokuapp.com
booker.username=admin
booker.password=password123

graphql.base-url=https://eu-central-1-shared-euc1-02.cdn.hygraph.com/content/clv6lwqu7000001w690st4vix/master

ui.base-url=https://demoqa.com
